name: mvi_poc
description: proof of mvi concept

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
